#!/usr/bin/env bash
# Fail if checked source/config files exceed MAX_LINES (default 600).
# Markdown is exempt. Generated and build artifacts are exempt.
set -euo pipefail

MAX_LINES="${MAX_FILE_LINES:-600}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

is_exempt() {
  local f="$1"
  case "$f" in
    *.md|*.MD|*.markdown|*.MARKDOWN) return 0 ;;
    bun.lock|package-lock.json|yarn.lock|pnpm-lock.yaml) return 0 ;;
    dist/*|build/*|node_modules/*|.convex/*) return 0 ;;
    convex/_generated/*) return 0 ;;
    RESEARCH/herdr-api.schema.json) return 0 ;;
    RESEARCH/API-METHODS.md) return 0 ;;
  esac
  if head -n 5 "$f" 2>/dev/null | grep -qE 'Code generated|@generated|autogenerated'; then
    return 0
  fi
  return 1
}

should_check() {
  local f="$1"
  [[ -f "$f" ]] || return 1
  is_exempt "$f" && return 1
  case "$f" in
    *.ts|*.tsx|*.mts|*.cts|*.js|*.mjs|*.cjs)
      return 0 ;;
    *.toml|*.yaml|*.yml|*.json)
      return 0 ;;
    *.sh|*.bash|*.py)
      return 0 ;;
    *) return 1 ;;
  esac
}

check_file() {
  local f="$1"
  local lines
  lines="$(wc -l <"$f" | tr -d '[:space:]')"
  if (( lines > MAX_LINES )); then
    echo "ERROR: $f has ${lines} lines (max ${MAX_LINES})" >&2
    return 1
  fi
  return 0
}

collect_staged_files() {
  git diff --cached --name-only --diff-filter=ACMR
}

collect_rev_files() {
  git diff --name-only --diff-filter=ACMR "$1"
}

collect_tracked_files() {
  git ls-files
}

run_on_files() {
  local failed=0
  local f
  while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    if should_check "$f"; then
      check_file "$f" || failed=1
    fi
  done
  return "$failed"
}

usage() {
  cat <<EOF
Usage: $(basename "$0") [--staged | --rev RANGE | --files FILE... | --all]

  --staged     Check staged files (pre-commit)
  --rev RANGE  Check files changed in git rev range (pre-push)
  --files      Check explicit paths
  --all        Check all tracked files (default)
EOF
}

main() {
  local mode="all"
  local range=""
  local -a explicit=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --staged) mode="staged"; shift ;;
      --rev) mode="rev"; range="${2:?--rev requires a range}"; shift 2 ;;
      --files) mode="files"; shift; explicit=("$@"); break ;;
      --all) mode="all"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
  done

  local failed=0
  case "$mode" in
    staged)
      collect_staged_files | run_on_files || failed=1
      ;;
    rev)
      collect_rev_files "$range" | run_on_files || failed=1
      ;;
    files)
      printf '%s\n' "${explicit[@]}" | run_on_files || failed=1
      ;;
    all)
      collect_tracked_files | run_on_files || failed=1
      ;;
  esac

  if (( failed )); then
    echo >&2
    echo "Split the file at a natural seam (see AGENTS.md §2). Markdown and generated/build paths are exempt." >&2
    exit 1
  fi
}

main "$@"
