import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version as string;
const builtAt = new Date().toISOString();

function git(args: string) {
  try { return execSync(`git ${args}`, { cwd: root, encoding: "utf8" }).trim(); }
  catch { return ""; }
}

const commit = git("rev-parse --short=12 HEAD") || "unknown";
const dirty = git("status --porcelain").length > 0;
const out = join(root, "src/buildInfo.generated.ts");
writeFileSync(out, `/** Generated by scripts/write-build-info.ts; do not edit. */
export const buildInfo = {
  version: ${JSON.stringify(version)},
  builtAt: ${JSON.stringify(builtAt)},
  commit: ${JSON.stringify(commit)},
  dirty: ${dirty},
} as const;
`);
